development:
  adapter: postgresql
  encoding: unicode
  username: rails2
  password: rails2
  host: 127.0.0.1
  port: 5432
  database: shopshopd
  pool: 20
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: 127.0.0.1
  port: 5432
  database: shopshopt
  pool: 5
  timeout: 5000

production:
    adapter: postgresql
    encoding: unicode
    username: postgres
    password: password
    host: 127.0.0.1
    port: 5432
    database: shopshopp
    pool: 5
    timeout: 5000
